name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Deno
      uses: denoland/setup-deno@0df5d9c641efdff149993c321fc27c11c5df8623  # v1.1.3
      with:
        deno-version: v1.x
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
    - run: npm run build
